# Generated by Django 4.1.4 on 2023-01-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(db_column='change_name', help_text='Book name', max_length=200, unique=True, unique_for_date='published_date', verbose_name='book name')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('key', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(help_text='name', max_length=50)),
                ('field_2', models.IntegerField(default=10)),
                ('field_3', models.FloatField(null=True)),
                ('field_5', models.DateTimeField(auto_now_add=True)),
                ('field_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.product')),
            ],
        ),
    ]
