# Generated by Django 4.1.4 on 2023-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='changed_count',
        ),
        migrations.AlterField(
            model_name='employer',
            name='boss',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='slaves', to='bboard.employer'),
        ),
    ]
