# Generated by Django 4.1.4 on 2023-01-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
