# Generated by Django 4.1.4 on 2023-01-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_delete_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(help_text='field_1', max_length=50)),
                ('field_2', models.IntegerField(default=10)),
                ('field_3', models.FloatField(null=True)),
                ('field_5', models.DateTimeField(auto_now_add=True)),
                ('field_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.product')),
            ],
        ),
    ]
